-- Script SQL pour insérer 20 produits avec images
-- À exécuter directement dans phpMyAdmin ou un client MySQL

INSERT INTO products (name, slug, description_fr, description_en, ingredients_fr, ingredients_en, price, weight, stock_quantity, image_url, is_available, is_featured, category_id, created_at) VALUES
('Confiture de Mangue', 'confiture-mangue', 'Confiture artisanale préparée avec des mangues fraîches du Sénégal, sucrée juste à point.', 'Artisanal jam made with fresh Senegalese mangoes, perfectly sweetened.', 'Mangue, sucre de canne, citron, vanille', 'Mango, cane sugar, lemon, vanilla', 2500, '250g', 50, 'confiture-mangue.jpg', 1, 1, 1, NOW()),
('Confiture de Gingembre', 'confiture-gingembre', 'Confiture épicée au gingembre frais, idéale pour les matins d''hiver.', 'Spiced jam with fresh ginger, perfect for winter mornings.', 'Gingembre, sucre, citron vert, miel', 'Ginger, sugar, green lemon, honey', 3000, '250g', 30, 'confiture-gingembre.jpg', 1, 0, 1, NOW()),
('Jus de Bissap', 'jus-bissap', 'Jus rafraîchissant préparé à partir des fleurs d''hibiscus séchées.', 'Refreshing juice made from dried hibiscus flowers.', 'Fleurs d''hibiscus, sucre, eau, menthe', 'Hibiscus flowers, sugar, water, mint', 1500, '1L', 40, 'jus-bissap-JUS_BI02.jpg', 1, 1, 1, NOW()),
('Jus de Bouye', 'jus-bouye', 'Jus de baobab riche en vitamine C, naturellement sucré.', 'Baobab juice rich in vitamin C, naturally sweetened.', 'Pulpe de baobab, eau, sucre, citron', 'Baobab pulp, water, sugar, lemon', 1800, '1L', 35, 'jus-bouye.jpg', 1, 0, 1, NOW()),
('Sirop de Tamarin', 'sirop-tamarin', 'Sirop sucré et acidulé à base de fruits de tamarin.', 'Sweet and tangy syrup made from tamarind fruits.', 'Fruits de tamarin, sucre, eau, cardamome', 'Tamarind fruits, sugar, water, cardamom', 3500, '500ml', 25, 'sirop-tamarin.jpg', 1, 0, 1, NOW()),
('Poudre de Moringa', 'poudre-moringa', 'Poudre de feuilles de moringa séchées, riche en nutriments.', 'Dried moringa leaf powder, rich in nutrients.', 'Feuilles de moringa séchées, 100% naturel', 'Dried moringa leaves, 100% natural', 4000, '200g', 60, 'poudre-moringa.jpg', 1, 1, 1, NOW()),
('Confiture de Papaye', 'confiture-papaye', 'Confiture douce et parfumée à la papaye mûre.', 'Sweet and fragrant papaya jam.', 'Papaye, sucre, jus de citron, gousse de vanille', 'Papaya, sugar, lemon juice, vanilla pod', 2200, '250g', 45, 'confiture-papaye.jpg', 1, 0, 1, NOW()),
('Jus de Ditakh', 'jus-ditakh', 'Jus traditionnel sénégalais à base de fruit du baobab.', 'Traditional Senegalese juice made from baobab fruit.', 'Pulpe de ditakh, eau, sucre, arôme naturel', 'Ditakh pulp, water, sugar, natural flavor', 1200, '1L', 20, 'jus-ditakh.jpg', 1, 0, 1, NOW()),
('Sirop de Gingembre', 'sirop-gingembre', 'Sirop concentré au gingembre, parfait pour les boissons chaudes.', 'Concentrated ginger syrup, perfect for hot drinks.', 'Gingembre frais, sucre, eau, citron', 'Fresh ginger, sugar, water, lemon', 2800, '250ml', 40, 'jus-gingembre-JUS_GI02.jpg', 1, 1, 1, NOW()),
('Miel du Sahel', 'miel-sahel', 'Miel naturel récolté dans les régions du Sahel sénégalais.', 'Natural honey harvested in the Senegalese Sahel regions.', 'Miel 100% pur, non filtré', '100% pure honey, unfiltered', 6000, '500g', 15, 'miel-sahel.jpg', 1, 0, 1, NOW()),
('Pâte d''Arachide', 'pate-arachide', 'Pâte d''arachide artisanale grillée et moulue.', 'Artisanal roasted and ground peanut paste.', 'Arachides grillées, huile d''arachide, sel', 'Roasted peanuts, peanut oil, salt', 2000, '300g', 55, 'pate-arachide.jpg', 1, 0, 1, NOW()),
('Confiture d''Ananas', 'confiture-ananas', 'Confiture tropicale à l''ananas doux et juteux.', 'Tropical jam with sweet and juicy pineapple.', 'Ananas, sucre, jus de citron, rhum', 'Pineapple, sugar, lemon juice, rum', 2400, '250g', 38, 'confiture-ananas.jpg', 1, 0, 1, NOW()),
('Jus de Fruit de la Passion', 'jus-fruit-passion', 'Jus exotique au fruit de la passion, légèrement acidulé.', 'Exotic passion fruit juice, slightly tangy.', 'Fruit de la passion, sucre, eau, menthe', 'Passion fruit, sugar, water, mint', 3200, '1L', 25, 'jus-fruit-passion.jpg', 1, 1, 1, NOW()),
('Confiture de Goyave', 'confiture-goyave', 'Confiture sucrée à la goyave verte, saveur unique.', 'Sweet green guava jam, unique flavor.', 'Goyave, sucre, jus de citron vert', 'Guava, sugar, green lemon juice', 2100, '250g', 42, 'confiture-goyave.jpg', 1, 0, 1, NOW()),
('Thé à la Menthe', 'the-menthe', 'Thé vert infusé à la menthe fraîche des jardins locaux.', 'Green tea infused with fresh mint from local gardens.', 'Thé vert, menthe fraîche, sucre optionnel', 'Green tea, fresh mint, optional sugar', 800, '20 sachets', 80, 'the-menthe.jpg', 1, 0, 1, NOW()),
('Jus d''Orange', 'jus-orange', 'Jus d''orange pressé froid, 100% naturel.', 'Cold-pressed orange juice, 100% natural.', 'Oranges fraîches, non sucré', 'Fresh oranges, unsweetened', 1000, '1L', 60, 'jus-orange.jpg', 1, 0, 1, NOW()),
('Confiture Mixte Tropicale', 'confiture-mix-tropicale', 'Mélange exotique de mangue, ananas et fruit de la passion.', 'Exotic mix of mango, pineapple and passion fruit.', 'Mangue, ananas, fruit de la passion, sucre, citron', 'Mango, pineapple, passion fruit, sugar, lemon', 2800, '250g', 30, 'confiture-mix-tropicale.jpg', 1, 1, 1, NOW()),
('Poudre de Baobab', 'poudre-baobab', 'Poudre de fruit de baobab riche en fibres et vitamines.', 'Baobab fruit powder rich in fiber and vitamins.', 'Fruit de baobab séché, 100% naturel', 'Dried baobab fruit, 100% natural', 3500, '250g', 35, 'poudre-baobab.jpg', 1, 0, 1, NOW()),
('Jus de Tamarin', 'jus-tamarin', 'Jus sucré et acidulé de tamarin, rafraîchissant.', 'Sweet and tangy tamarind juice, refreshing.', 'Fruits de tamarin, eau, sucre, glace', 'Tamarind fruits, water, sugar, ice', 1600, '1L', 28, 'jus-tamarin.jpg', 1, 0, 1, NOW()),
('Mélange de Thés Sénégalais', 'melange-the-senegalais', 'Mélange traditionnel de thé vert, bissap et gingembre.', 'Traditional blend of green tea, hibiscus and ginger.', 'Thé vert, fleurs d''hibiscus, gingembre, menthe', 'Green tea, hibiscus flowers, ginger, mint', 1500, '25 sachets', 45, 'melange-the-senegalais.jpg', 1, 1, 1, NOW());
