-- ============================================================
-- GIE Sokhna Maï - Données de test
-- ============================================================

USE gie_sokhna_mai;

-- ============================================================
-- PRODUITS
-- ============================================================
INSERT INTO products (category_id, name, slug, description_fr, description_en, ingredients_fr, ingredients_en, price, weight, stock_quantity, image_url, is_available, is_featured, created_at) VALUES
(1, 'Confiture de Mangue', 'confiture-de-mangue', 'Confiture artisanale préparée avec des mangues fraîches du Sénégal. Un délice sucré au goût authentique.', 'Artisanal jam made with fresh Senegalese mangoes. A sweet delight with authentic taste.', 'Mangue, sucre, citron', 'Mango, sugar, lemon', 2500, '250g', 50, 'confiture-mangue.jpg', TRUE, TRUE, '2024-01-15'),
(1, 'Confiture de Gingembre', 'confiture-de-gingembre', 'Une confiture épicée au gingembre frais, parfaite pour les amateurs de saveurs audacieuses.', 'A spicy jam made with fresh ginger, perfect for lovers of bold flavors.', 'Gingembre, sucre, citron', 'Ginger, sugar, lemon', 3000, '250g', 30, 'confiture-gingembre.jpg', TRUE, TRUE, '2024-01-15'),
(1, 'Confiture de Pamplemousse', 'confiture-de-pamplemousse', 'Confiture acidulée au pamplemousse, idéale pour le petit-déjeuner.', 'Tangy grapefruit jam, ideal for breakfast.', 'Pamplemousse, sucre', 'Grapefruit, sugar', 2800, '250g', 25, 'confiture-pamplemousse.jpg', TRUE, FALSE, '2024-01-15'),
(1, 'Confiture de Tamarin', 'confiture-de-tamarin', 'Confiture exotique au tamarin, un goût unique qui surprendra vos papilles.', 'Exotic tamarind jam, a unique taste that will surprise your taste buds.', 'Tamarin, sucre, épices', 'Tamarind, sugar, spices', 2500, '250g', 20, 'confiture-tamarin.jpg', TRUE, FALSE, '2024-01-15'),
(1, 'Confiture de Citron', 'confiture-de-citron', 'Confiture rafraîchissante au citron, parfaite pour accompagner vos thés.', 'Refreshing lemon jam, perfect to accompany your teas.', 'Citron, sucre, gingembre', 'Lemon, sugar, ginger', 2400, '250g', 35, 'confiture-citron.jpg', TRUE, FALSE, '2024-01-15'),
(1, 'Confiture de Papaye', 'confiture-de-papaye', 'Confiture de papaye, fruit tropical aux saveurs ensoleillées.', 'Papaya jam, a tropical fruit with sunny flavors.', 'Papaye, sucre, vanille', 'Papaya, sugar, vanilla', 2300, '250g', 40, 'confiture-papaye.jpg', TRUE, FALSE, '2024-01-15'),
(1, 'Confiture de Baobab', 'confiture-de-baobab', 'Confiture originale au fruit de baobab, riche en vitamine C.', 'Original jam made with baobab fruit, rich in vitamin C.', 'Pulpe de baobab, sucre', 'Baobab pulp, sugar', 3200, '250g', 15, 'confiture-baobab.jpg', TRUE, TRUE, '2024-01-15'),
(2, 'Jus de Bissap', 'jus-de-bissap', 'Jus traditionnel à base d\'hibiscus, rafraîchissant et riche en antioxydants.', 'Traditional hibiscus-based juice, refreshing and rich in antioxidants.', 'Bissap, sucre, eau', 'Hibiscus, sugar, water', 1500, '500ml', 100, 'jus-bissap.jpg', TRUE, TRUE, '2024-01-15'),
(2, 'Jus de Bouye', 'jus-de-bouye', 'Jus de baobab crémeux et nutritif, une boisson énergisante.', 'Creamy and nutritious baobab juice, an energizing drink.', 'Pulpe de bouye, sucre, eau', 'Baobab pulp, sugar, water', 2000, '500ml', 80, 'jus-bouye.jpg', TRUE, TRUE, '2024-01-15'),
(2, 'Jus de Gingembre', 'jus-de-gingembre', 'Jus de gingembre piquant et revigorant, excellent pour la santé.', 'Spicy and invigorating ginger juice, excellent for health.', 'Gingembre, citron, sucre, eau', 'Ginger, lemon, sugar, water', 1500, '500ml', 90, 'jus-gingembre.jpg', TRUE, FALSE, '2024-01-15'),
(3, 'Sirop de Gingembre', 'sirop-de-gingembre', 'Sirop concentré de gingembre à diluer dans de l\'eau ou des boissons.', 'Concentrated ginger syrup to dilute in water or beverages.', 'Gingembre, sucre, citron', 'Ginger, sugar, lemon', 3000, '500ml', 45, 'sirop-gingembre.jpg', TRUE, TRUE, '2024-01-15'),
(3, 'Sirop de Bissap', 'sirop-de-bissap', 'Sirop concentré de bissap pour préparer de délicieuses boissons.', 'Concentrated hibiscus syrup for preparing delicious drinks.', 'Bissap, sucre, citron', 'Hibiscus, sugar, lemon', 2500, '500ml', 60, 'sirop-bissap.jpg', TRUE, FALSE, '2024-01-15'),
(4, 'Poudre de Moringa', 'poudre-de-moringa', 'Poudre de feuilles de moringa, super-aliment riche en nutriments.', 'Moringa leaf powder, a nutrient-rich superfood.', 'Feuilles de moringa séchées', 'Dried moringa leaves', 2500, '250g', 40, 'poudre-moringa.jpg', TRUE, TRUE, '2024-01-15'),
(4, 'Graines de Lin', 'graines-de-lin', 'Graines de lin doré, riches en oméga-3 et fibres.', 'Golden flax seeds, rich in omega-3 and fiber.', 'Graines de lin', 'Flax seeds', 1800, '250g', 50, 'graines-lin.jpg', TRUE, FALSE, '2024-01-15');

-- ============================================================
-- ÉQUIPE
-- ============================================================
INSERT INTO team_members (name, role_fr, role_en, description_fr, description_en, photo_url, email, display_order, is_active) VALUES
('Amy NIOME', 'Présidente', 'President', 'Leader visionnaire du GIE Sokhna Maï, elle guide l\'association vers l\'excellence.', 'Visionary leader of GIE Sokhna Maï, guiding the association toward excellence.', 'team-amy.jpg', 'amy@sokhnamai.sn', 1, TRUE),
('Angélique TOURE', 'Vice-Présidente', 'Vice-President', 'Bras droit de la présidente, elle coordonne les opérations quotidiennes.', 'Right hand of the president, coordinating daily operations.', 'team-angelique.jpg', 'angelique@sokhnamai.sn', 2, TRUE),
('Anna NDIAYE', 'Trésorière', 'Treasurer', 'Gestion rigoureuse des finances et transparence comptable.', 'Rigorous financial management and accounting transparency.', 'team-anna.jpg', 'anna@sokhnamai.sn', 3, TRUE),
('Magou SAMB', 'Gérante de Boutique', 'Shop Manager', 'Service client au quotidien, elle assure la satisfaction de nos clients.', 'Daily customer service, ensuring client satisfaction.', 'team-magou.jpg', 'magou@sokhnamai.sn', 4, TRUE);

-- ============================================================
-- ARTICLES DE BLOG
-- ============================================================
INSERT INTO blog_posts (category_id, author_id, title_fr, title_en, slug, excerpt_fr, excerpt_en, content_fr, content_en, emoji, is_published, published_at, created_at) VALUES
(1, 1, 'Les bienfaits du Moringa : un super aliment à découvrir', 'The benefits of Moringa: a superfood to discover', 'bienfaits-moringa-super-aliment', 'Le moringa est considéré comme l\'un des super aliments les plus complets. Riche en vitamines, minéraux et antioxydants, découvrez pourquoi il est surnommé "l\'arbre miracle".', 'Moringa is considered one of the most complete superfoods. Rich in vitamins, minerals and antioxidants, discover why it is called "the miracle tree".', '<p>Le moringa oleifera, souvent appelé "l\'arbre miracle", est une plante originaire d\'Inde mais qui pousse également très bien en Afrique de l\'Ouest. Ses feuilles sont d\'une valeur nutritionnelle exceptionnelle.</p><h2>Riche en nutriments</h2><p>Les feuilles de moringa contiennent :</p><ul><li>7 fois plus de vitamine C que les oranges</li><li>4 fois plus de calcium que le lait</li><li>4 fois plus de vitamine A que les carottes</li><li>3 fois plus de potassium que les bananes</li><li>2 fois plus de protéines que le yaourt</li></ul>', '<p>Moringa oleifera, often called the "miracle tree", is a plant native to India but also grows well in West Africa. Its leaves have exceptional nutritional value.</p><h2>Rich in nutrients</h2><p>Moringa leaves contain:</p><ul><li>7 times more vitamin C than oranges</li><li>4 times more calcium than milk</li><li>4 times more vitamin A than carrots</li><li>3 times more potassium than bananas</li><li>2 times more protein than yogurt</li></ul>', '🌿', TRUE, '2026-03-15 08:00:00', '2026-03-15'),
(2, 1, 'Recette : Smoothie Bouye-Mangue rafraîchissant', 'Recipe: Refreshing Bouye-Mango Smoothie', 'recette-smoothie-bouye-mangue', 'Préparez un délicieux smoothie en combinant notre jus de bouye avec de la mangue fraîche. Une recette simple et nutritive pour toute la famille.', 'Prepare a delicious smoothie by combining our bouye juice with fresh mango. A simple and nutritious recipe for the whole family.', '<h2>Ingrédients (pour 2 personnes)</h2><ul><li>250ml de jus de bouye</li><li>1 mangue mûre</li><li>1 banane</li><li>1 yaourt nature</li><li>Miel au goût</li><li>Glaçons</li></ul><h2>Préparation</h2><p>Mixez tous les ingrédients jusqu\'à obtenir une consistance lisse. Servez immédiatement bien frais.</p>', '<h2>Ingredients (for 2 people)</h2><ul><li>250ml of bouye juice</li><li>1 ripe mango</li><li>1 banana</li><li>1 plain yogurt</li><li>Honey to taste</li><li>Ice cubes</li></ul><h2>Preparation</h2><p>Blend all ingredients until smooth. Serve immediately while chilled.</p>', '🥤', TRUE, '2026-03-10 10:00:00', '2026-03-10'),
(3, 1, 'GIE Sokhna Maï à la Foire Internationale de Dakar', 'GIE Sokhna Maï at the Dakar International Fair', 'sokhna-mai-fidak-2025', 'Notre groupement a participé à la FIDAK cette année avec un stand dédié à nos produits transformés. Un succès retentissant !', 'Our group participated in FIDAK this year with a dedicated stand for our processed products. A resounding success!', '<p>Cette année, le GIE Sokhna Maï a eu l\'honneur de participer à la Foire Internationale de Dakar (FIDAK). Notre stand, situé dans le hall des produits locaux, a attiré de nombreux visiteurs curieux de découvrir nos confitures artisanales et nos jus naturels.</p><h2>Un succès commercial</h2><p>Au cours des 10 jours de la foire, nous avons :</p><ul><li>Vendu plus de 500 unités de produits</li><li>Établi 15 partenariats commerciaux</li><li>Recruté 3 nouveaux membres pour le GIE</li></ul>', '<p>This year, GIE Sokhna Maï had the honor of participating in the Dakar International Fair (FIDAK). Our stand, located in the local products hall, attracted many visitors curious to discover our artisanal jams and natural juices.</p><h2>A commercial success</h2><p>During the 10 days of the fair, we:</p><ul><li>Sold over 500 product units</li><li>Established 15 commercial partnerships</li><li>Recruited 3 new members for the GIE</li></ul>', '🎪', TRUE, '2026-03-05 14:00:00', '2026-03-05'),
(4, 1, 'Le Bissap : de la fleur au verre', 'Bissap: from flower to glass', 'bissap-fleur-au-verre', 'Découvrez comment nous transformons les fleurs d\'hibiscus en un délicieux jus de bissap. Le processus complet de fabrication artisanale.', 'Discover how we transform hibiscus flowers into a delicious bissap juice. The complete artisanal manufacturing process.', '<h2>Récolte</h2><p>Les fleurs d\'hibiscus sont récoltées à maturité dans les jardins de nos membres. Seules les fleurs les plus belles sont sélectionnées.</p><h2>Séchage</h2><p>Les fleurs sont séchées à l\'ombre pendant 3 à 5 jours pour préserver leurs propriétés.</p><h2>Infusion</h2><p>Les fleurs séchées sont infusées dans de l\'eau chaude pour extraire leur couleur et leurs saveurs.</p>', '<h2>Harvest</h2><p>Hibiscus flowers are harvested at maturity in our members\' gardens. Only the most beautiful flowers are selected.</p><h2>Drying</h2><p>The flowers are dried in the shade for 3 to 5 days to preserve their properties.</p><h2>Infusion</h2><p>The dried flowers are infused in hot water to extract their color and flavors.</p>', '🌺', TRUE, '2026-02-28 09:00:00', '2026-02-28'),
(5, 1, '5 façons d\'utiliser le sirop de gingembre au quotidien', '5 ways to use ginger syrup daily', '5-facons-sirop-gingembre', 'Au-delà de la simple boisson, le sirop de gingembre peut agrémenter vos plats, desserts et soins. Découvrez nos astuces !', 'Beyond a simple drink, ginger syrup can enhance your dishes, desserts and wellness routines. Discover our tips!', '<h2>1. En boisson chaude</h2><p>Ajoutez 2 cuillères à soupe dans une tasse d\'eau chaude pour une infusion revigorante.</p><h2>2. Dans les vinaigrettes</h2><p>Mélangez avec du vinaigre et de l\'huile pour une vinaigrette épicée.</p><h2>3. Sur les desserts</h2><p>Arrosez une boule de glace vanille pour un dessert original.</p><h2>4. Dans les marinades</h2><p>Utilisez comme base pour mariner viandes et poissons.</p><h2>5. Pour la santé</h2><p>Prenez une cuillère pure au réveil pour stimuler votre digestion.</p>', '<h2>1. As a hot drink</h2><p>Add 2 tablespoons to a cup of hot water for an invigorating infusion.</p><h2>2. In salad dressings</h2><p>Mix with vinegar and oil for a spicy dressing.</p><h2>3. On desserts</h2><p>Drizzle over vanilla ice cream for an original dessert.</p><h2>4. In marinades</h2><p>Use as a base for marinating meats and fish.</p><h2>5. For health</h2><p>Take a spoonful pure upon waking to stimulate digestion.</p>', '🫚', TRUE, '2026-02-20 11:00:00', '2026-02-20'),
(6, 1, 'Témoignage : Awa, femme entrepreneure du GIE', 'Testimony: Awa, woman entrepreneur of the GIE', 'temoignage-awa-entrepreneure', 'Awa nous raconte son parcours au sein du GIE Sokhna Maï et comment la transformation des produits locaux a changé sa vie.', 'Awa tells us about her journey within GIE Sokhna Maï and how local product transformation changed her life.', '<p>Awa Diallo, 35 ans, mère de trois enfants, a rejoint le GIE Sokhna Maï il y a deux ans. Aujourd\'hui, elle dirige l\'unité de production des confitures.</p><h2>Un parcours inspirant</h2><p>"Avant de rejoindre le GIE, je vendais des fruits sur le marché. Les revenus étaient irréguliers. Depuis que j\'ai appris la transformation, mes revenus ont triplé et je peux payer les études de mes enfants."</p><h2>Formation et autonomie</h2><p>Le GIE offre une formation continue à tous ses membres. Awa a appris la fabrication des confitures, la gestion des stocks et même les bases de la comptabilité.</p>', '<p>Awa Diallo, 35 years old, mother of three children, joined GIE Sokhna Maï two years ago. Today, she heads the jam production unit.</p><h2>An inspiring journey</h2><p>"Before joining the GIE, I sold fruit at the market. Income was irregular. Since I learned processing, my income has tripled and I can pay for my children\'s education."</p><h2>Training and autonomy</h2><p>The GIE offers continuous training to all its members. Awa learned how to make jams, manage inventory, and even basic accounting.</p>', '👩🏾', TRUE, '2026-02-15 08:30:00', '2026-02-15');

-- ============================================================
-- CLIENTS
-- ============================================================
INSERT INTO customers (name, phone, email, address, city, notes, created_at) VALUES
('Fatou Diallo', '+221 77 123 45 67', 'fatou@email.com', '123 Rue de la Paix', 'Dakar', 'Cliente régulière', '2024-01-10'),
('Amadou Sow', '+221 76 234 56 78', NULL, '456 Avenue Faidherbe', 'Thiès', 'Préfère les livraisons le weekend', '2024-01-11'),
('Marie Ndiaye', '+221 70 345 67 89', 'marie@email.com', '789 Boulevard du Centenaire', 'Dakar', '', '2024-01-12'),
('Ousmane Ba', '+221 78 456 78 90', NULL, '321 Rue des Almadies', 'Dakar', 'Client grossiste', '2024-01-13'),
('Aïda Fall', '+221 76 567 89 01', 'aida@email.com', '654 Avenue Cheikh Anta Diop', 'Rufisque', '', '2024-01-14');

-- ============================================================
-- COMMANDES
-- ============================================================
INSERT INTO orders (order_number, customer_id, status, total_amount, delivery_address, delivery_city, delivery_notes, payment_method, payment_status, whatsapp_sent, processed_by, created_at) VALUES
('CMD-2024-001', 1, 'Livrée', 6000, '123 Rue de la Paix', 'Dakar', '', 'Mobile Money', 'Payée', TRUE, 1, '2024-01-15 10:30:00'),
('CMD-2024-002', 2, 'En préparation', 7500, '456 Avenue Faidherbe', 'Thiès', 'Livraison express', 'Espèces', 'En attente', FALSE, 1, '2024-01-15 14:20:00'),
('CMD-2024-003', 3, 'En attente', 3000, '789 Boulevard du Centenaire', 'Dakar', '', 'Mobile Money', 'En attente', FALSE, 1, '2024-01-16 09:15:00'),
('CMD-2024-004', 4, 'Confirmée', 12000, '321 Rue des Almadies', 'Dakar', '', 'Virement', 'Payée', TRUE, 1, '2024-01-16 11:45:00'),
('CMD-2024-005', 5, 'En livraison', 5000, '654 Avenue Cheikh Anta Diop', 'Rufisque', '', 'Mobile Money', 'Payée', TRUE, 1, '2024-01-16 15:30:00');

-- ============================================================
-- LIGNES DE COMMANDE
-- ============================================================
INSERT INTO order_items (order_id, product_id, quantity, unit_price, weight, subtotal, notes) VALUES
(1, 8, 2, 3000, '500ml', 6000, ''),  -- Jus de Bissap
(2, 1, 3, 2500, '250g', 7500, 'Cadeau pour anniversaire'),
(3, 10, 1, 3000, '500ml', 3000, ''),
(4, 8, 4, 3000, '500ml', 12000, 'Commande pour événement'),
(5, 12, 2, 2500, '250g', 5000, '');  -- Poudre de Moringa

-- ============================================================
-- PARTENAIRES
-- ============================================================
INSERT INTO partners (name, name_en, type, year, date_fr, date_en, description_fr, description_en, logo_url, website_url, display_order, is_active) VALUES
('Foire de l\'Innovation', 'Innovation Fair', 'Événement', '2021', 'Décembre 2021', 'December 2021', 'Première participation à une foire majeure pour présenter nos produits au grand public.', 'First participation in a major fair to present our products to the general public.', 'foire-innovation.png', NULL, 1, TRUE),
('Marché des Producteurs Locaux', 'Local Producers Market', 'Partenaire', '2022', 'Tous les samedis', 'Every Saturday', 'Présence régulière sur le marché des producteurs locaux de Dakar.', 'Regular presence at the local producers market in Dakar.', NULL, NULL, 2, TRUE),
('HUMASOL', 'HUMASOL', 'Partenaire', '2023', 'Partenariat depuis 2023', 'Partnership since 2023', 'Collaboration avec HUMASOL pour le développement de projets solaires dans nos unités de production.', 'Collaboration with HUMASOL for the development of solar projects in our production units.', 'humasol-logo.png', 'https://humasol.be', 3, TRUE);

-- ============================================================
-- MESSAGES DE CONTACT
-- ============================================================
INSERT INTO contact_messages (name, email, phone, subject, message, ip_address, is_read, created_at) VALUES
('Jean Dupont', 'jean.dupont@example.com', '+221 77 111 22 33', 'Demande de partenariat', 'Bonjour, je souhaite devenir distributeur de vos produits dans la région de Thiès. Pouvons-nous organiser un rendez-vous ?', '192.168.1.1', FALSE, '2024-01-20 09:15:00'),
('Marie Curie', 'marie.curie@example.com', NULL, 'Question sur les confitures', 'Quelle est la durée de conservation de vos confitures ? Sont-elles sans conservateurs ?', '192.168.1.2', TRUE, '2024-01-19 14:30:00'),
('Pierre Martin', 'pierre.martin@example.com', '+221 76 444 55 66', 'Commande en gros', 'Je souhaite passer une commande de 50 pots de confiture pour un événement. Avez-vous des tarifs dégressifs ?', '192.168.1.3', FALSE, '2024-01-18 11:00:00');
